### ISSUE TITLE
Bug: jekyll-target-blank breaks build on Ubuntu

### ISSUE THREAD

**Issue by bittlingmayer** [machinetranslate/machinetranslate.org#490]
**Description:** On Ubuntu, .md files with non-ASCII characters break the build

**Steps to reproduce the behavior:**
```bash
bundle exec jekyll serve
```

**Screenshots [optional]:**

```bash
  Pre-Render Hooks: apis/youdao.md
  Rendering Markup: apis/youdao.md
  Rendering Layout: apis/youdao.md
     Layout source: site
jekyll 3.9.3 | Error:  URI must be ascii only "https://ai.youdao.com/DOCSIRMA/html/\u81EA\u7136\u8BED\u8A00\u7FFB\u8BD1/API\u6587\u6863/\u6587\u672C\u7FFB\u8BD1\u670D\u52A1/\u6587\u672C\u7FFB\u8BD1\u670D\u52A1-API\u6587\u6863.html"
/usr/local/lib/ruby/3.1.0/uri/rfc3986_parser.rb:21:in `split': URI must be ascii only "https://ai.youdao.com/DOCSIRMA/html/\\u81EA\\u7136\\u8BED\\u8A00\\u7FFB\\u8BD1/API\\u6587\\u6863/\\u6587\\u672C\\u7FFB\\u8BD1\\u670D\\u52A1/\\u6587\\u672C\\u7FFB\\u8BD1\\u670D\\u52A1-API\\u6587\\u6863.html" (URI::InvalidURIError)
  from /usr/local/lib/ruby/3.1.0/uri/rfc3986_parser.rb:72:in `parse'
```

**Device:**
 - Ubuntu:
 - Ruby version: 3.2.0
 - Jekyll version: 

**Additional context:**

It works on GitHub CI and on other contributors' Mac and Windows machines.

https://github.com/keithmifsud/jekyll-target-blank/issues/33

**Comment by bittlingmayer** [comment]
So far, the workaround was just to disable that plugin locally, in both the _config.yml and the Gemfile.

**Comment by bittlingmayer** [comment]
@cefoo Had this issue too (on Windows)

**Comment by bittlingmayer** [comment]
We disabled it for now, but would be nice to add it back.
